config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'start_pages#show'

  resources :research_sessions, only: [:new, :create], path: 'research-sessions' do
    resources :questions, only: [:show, :update], controller: 'research_sessions/questions'
    get :preview
    post :create_a_copy
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get '*url' => 'errors#not_found'
end

app/models/research_session.rb
require 'securerandom'

class ResearchSession < ApplicationRecord
  before_create :set_slug_from_name!

  validates :name, presence: true

  validates :researcher_name, presence: true,
            if: -> (session) { session.reached_step?(:researcher) }
  validates :researcher_email, presence: true,
            if: -> (session) { session.reached_step?(:researcher) }
  validates :researcher_email, format: /\A\S+@\S+\Z/,
    if: -> (session) { session.researcher_email.present? && session.reached_step?(:researcher) }

  validates :topic, presence: true,
    if: -> (session) { session.reached_step?(:topic) }
  validates :purpose, presence: true,
    if: -> (session) { session.reached_step?(:topic) }

  validates :methodologies,
            has_at_least_one: { of: Methodologies.allowed_values },
            if: -> (session) { session.reached_step?(:methodologies) }
  validates :other_methodology, presence: true,
            if: lambda { |session|
              session.reached_step?(:methodologies) &&
                session.methodologies&.any? { |item| item.to_s == 'other' }
            }

  validates :other_recording_method, presence: true,
            if: lambda { |session|
              session.reached_step?(:recording) &&
                session.recording_methods&.any? { |item| item.to_s == 'other' }
            }
  validates :recording_methods,
            has_at_least_one: { of: RecordingMethods.allowed_values },
            if: -> (session) { session.reached_step?(:recording) }

  validates :shared_with, inclusion: { in: SharedWith.allowed_values },
            if: -> (session) { session.reached_step?(:storing) }

  validates :shared_duration, presence: true,
            if: -> (session) { session.reached_step?(:storing) }

  validates :travel_expenses_limit, numericality: true,
            if: -> (session) { session.expenses_validation(:travel_expenses_limit) }
  validates :food_expenses_limit, numericality: true,
            if: -> (session) { session.expenses_validation(:food_expenses_limit) }
  validates :other_expenses_limit, numericality: true,
            if: -> (session) { session.expenses_validation(:other_expenses_limit) }

  validates :payment_type, inclusion: { in: PaymentType.allowed_values },
            if: -> (session) { session.incentives_enabled && session.reached_step?(:incentives) }
  validates :incentive_value, presence: true, numericality: true,
            if: -> (session) { session.incentives_enabled && session.reached_step?(:incentives) }

  def previewable?
    status == Steps.instance.last.to_s
  end

  def reached_step?(step)
    Steps.instance.reached_step?(self, step)
  end

  def set_slug_from_name!
    return if name.blank?

    slug = name.strip.downcase.tr(' ', '-')
    slug = "#{slug}-#{SecureRandom.uuid}" if ResearchSession.exists?(slug: slug)
    self.slug = slug
  end

  def to_param
    slug
  end

  def expenses_validation(category)
    other_expenses_used = Expenses::CATEGORIES
                          .reject { |expense| expense == category }
                          .all? { |expense| send(expense).blank? }
    send(category).present? || (expenses_enabled && reached_step?(:expenses) && other_expenses_used)
  end
end

app/models/research_session/steps.rb
require 'singleton'

class ResearchSession
  class Steps
    include Singleton

    PARAMS = ActiveSupport::OrderedHash[{
      researcher: [:researcher_job_title, :researcher_name, :researcher_phone,
                   :researcher_email],
      topic: [:topic, :purpose],
      methodologies: [:other_methodology, methodologies: []],
      recording: [:other_recording_method, recording_methods: []],
      storing: [:shared_with, :shared_duration],
      where_when: [:where_when_enabled, :when_text, :duration, :location, :participant_equipment,
                   :food_provided],
      expenses: [:expenses_enabled, :travel_expenses_limit, :food_expenses_limit,
                 :other_expenses_limit, :receipts_required],
      incentives: [:incentives_enabled, :payment_type, :incentive_value]
    }]

    def reached_step?(session, step)
      step = step.to_sym
      return false if session.status == 'new'

      step_indices.fetch(session.status.to_sym) >= step_indices.fetch(step)
    end

    def step_keys
      @step_keys ||= PARAMS.keys
    end

    def first
      PARAMS.keys.first
    end

    def last
      PARAMS.keys.last
    end

    ##
    # Returns a hash of attribute names to step names in the wizard
    def attr_to_step(attr)
      @attrs_to_steps ||=
        PARAMS.each_with_object({}) do |kv, params_to_steps|
          step, params = *kv
          params.each do |param|
            case param
            when Symbol
              params_to_steps[param] = step
            when Hash
              param.each_key do |array_param|
                params_to_steps[array_param] = step
              end
            end
          end
        end
      @attrs_to_steps.fetch(attr)
    end

  private

    ##
    # A hash of step names as symbols to numeric indices, with age: 0, name: 1 etc
    def step_indices
      @step_indices ||= step_keys.each_with_index.map { |step, index| [step, index] }.to_h
    end
  end
end

app/controllers/research_sessions/questions_controller.rb
# frozen_string_literal: true

module ResearchSessions
  class QuestionsController < ApplicationController
    helper ResearchSessionsHelper

    include Wicked::Wizard
    steps(*ResearchSession::Steps::PARAMS.keys)

    rescue_from Wicked::Wizard::InvalidStepError do
      render status: 404,
             plain: %(Step "#{params[:id]}" not found)
    end

    def show
      @research_session = current_research_session
      render_wizard
    end

    def update
      @research_session = current_research_session
      @research_session.status = step unless @research_session.reached_step?(step)
      @research_session.assign_attributes(question_params)
      if returning_to_preview? && @research_session.save
        redirect_to(research_session_preview_path(@research_session))
      else
        render_wizard(@research_session)
      end
    end

    def finish_wizard_path
      research_session_preview_path
    end

    private

    def current_research_session
      ResearchSession.find_by(slug: params[:research_session_id])
    end

    def returning_to_preview?
      params['edit-preview'] == '1'
    end

    def question_params
      params.require(:research_session).permit(ResearchSession::Steps::PARAMS[step]).tap do |p|
        p['methodologies']&.reject!(&:blank?)
        p['recording_methods']&.reject!(&:blank?)

        %w[
          travel_expenses_limit
          food_expenses_limit
          other_expenses_limit
          incentive_value
        ].each do |attr|
          p[attr] = p[attr].delete('£') if p[attr]
        end
      end
    end
  end
end

app/controllers/research_sessions_controller.rb
# frozen_string_literal: true

class ResearchSessionsController < ApplicationController
  def new
    @research_session = ResearchSession.new
    return if params[:from_existing].blank?

    existing_session = ResearchSession.find_by!(slug: params[:from_existing])
    @existing_session_id = existing_session.slug
    proposed_new_name = "#{existing_session.name} (copy)"
    @research_session.name = proposed_new_name
    render 'create_a_copy'
  end

  def create
    @research_session = ResearchSession.new(session_creation_params)
    if @research_session.save
      redirect_to(first_question_path)
    else
      render :new
    end
  end

  def create_a_copy
    @research_session = ResearchSession.find_by!(slug: params[:research_session_id])

    plain_400 && return unless @research_session.previewable?

    @research_session.dup.tap do |new_research_session|
      new_research_session.assign_attributes(session_creation_params)
      new_research_session.set_slug_from_name!
      new_research_session.save!
      redirect_to(research_session_preview_path(new_research_session))
    end
  end

  def preview
    @research_session = current_research_session

    # Allow the user to pass a parameter to switch between over 18 and under 18 mode
    able_to_consent = params['able-to-consent'] == 'yes'

    @research_session = ResearchSessionPresenter.new(
      @research_session,
      able_to_consent: able_to_consent
    )
  end

  private

  def research_session_slug
    params[:research_session_id] || params[:id]
  end

  def session_creation_params
    params.require(:research_session).permit(:name)
  end

  def current_research_session
    ResearchSession.find_by!(slug: research_session_slug)
  end

  def first_question_path
    research_session_question_path(@research_session, id: ResearchSession::Steps.instance.first)
  end

  def plain_400
    render status: 400,
           plain: %(Research Session "#{research_session_slug}" can't have a copy yet)
  end
end

app/helpers/research_sessions_helper.rb
module ResearchSessionsHelper
  def edit_link_for(attr)
    step_for_attr = ResearchSession::Steps.instance.attr_to_step(attr)

    research_session_question_path(
      @research_session.slug, step_for_attr, 'edit-preview' => '1'
    )
  end

  def able_to_consent?
    @research_session.respond_to?(:able_to_consent?) ? @research_session.able_to_consent? : false
  end
end

app/views/research_sessions/_ok_cancel.html.erb
<p class="button-bar">
  <%= button_tag('Continue', type: :submit, class: 'button') %>
  <%= link_to 'Cancel', root_path, class: 'button button--secondary' %>
</p>

app/views/research_sessions/create_a_copy.html.erb
<%= c('Step') do %>
  <%= c('Title', text: 'Create a copy') %>

  <%= c('ErrorSummary', errors: @research_session.errors.to_hash) if @research_session.errors.any? %>

  <%= c('Form', action: research_session_create_a_copy_path(research_session_id: @existing_session_id)) do %>
    <%= c('SinglelineTextControl',
      id: 'research_session[name]',
      name: 'name',
      value: @research_session.name,
      label: t('research_session_attr_labels.name'),
      size: 48,
      errored: @research_session.errors['name'].present?,
      validation: @research_session.errors['name'][0]
    ) %>
    <%= c('Submit', text: 'Continue') %>
  <% end %>
<% end %>

app/views/research_sessions/data.html.erb
<%= render "research_sessions/progress" %>
<div class="main-content">
  <%= render 'error_summary' %>
  <h1 class="subtitle-large">Storing information</h1>
  <%= barnardos_form_with model: @research_session, url: wizard_path do |form| %>

    <%= form.radio_group_vertical \
        :shared_with,
        SharedWith::NAME_VALUES,
        { autofocus_first_item: true },
        legend: 'How will the information recorded in this session be stored and processed?'
    %>

    <%= form.labelled_text_field :shared_duration %>
    
    <%= form.labelled_text_area \
          :shared_use, text_options: { placeholder: 'The data will be used to...' }
    %>

    <%= render 'button_bar' %>
  <% end %>
</div>

app/views/research_sessions/expenses.html.erb
<%= render "research_sessions/progress" %>
<div class="main-content">
  <%= render 'error_summary' %>
  <h1 class="subtitle-large">Expenses</h1>
  <%= barnardos_form_with model: @research_session, url: wizard_path do |form| %>

      <%= form.labelled_text_field :travel_expenses_limit,
            text_options: { placeholder: '0.00', autofocus: true }
      %>

      <%= form.labelled_text_field :food_expenses_limit,
            text_options: { placeholder: '0.00' }
      %>

      <%= form.labelled_text_field :other_expenses_limit,
            text_options: { placeholder: '0.00' }
      %>

      <%= form.radio_group_vertical :receipts_required,
            { true => 'Yes', false => 'No' },
            legend: 'Must the participant provide a receipt for any expenses claimed?'
      %>

      <%= render 'button_bar' %>
  <% end %>
</div>

app/views/research_sessions/focus.erb
<%= render 'back_link' %>

<h2 class="heading-medium">Research Focus</h2>
<div class="main-content">
  <%= render 'error_summary' %>

  <%= form_for @research_session, url: wizard_path do %>
      <%= labelled_text_field_tag(
            :focus,
            'What is the focus of your research project?',
            @research_session.focus,
            label_options: {
                hint: 'What you are researching and why - e.g. Barnardoʼs ' \
                      'is currently doing some research about.' }
          )
      %>

      <%= render 'ok_cancel' %>
  <% end %>
</div>

app/views/research_sessions/incentive.html.erb
<%= render "research_sessions/progress" %>
<div class="main-content">
  <%= render 'error_summary' %>
  <h1 class="subtitle-large">Incentive</h1>
  <%= barnardos_form_with model: @research_session, url: wizard_path do |form| %>
      <%= form.radio_group_vertical :incentive,
          { true => 'Yes', false => 'No' },
          { autofocus_first_item: true },
          legend: 'Will an incentive be provided?'
      %>

      <%= form.radio_group_vertical :payment_type,
          PaymentType::NAME_VALUES,
          legend: 'What form will the incentive take?'
      %>

      <%= form.labelled_text_field :incentive_value %>

      <%= render 'button_bar' %>
  <% end %>
</div>

app/views/research_sessions/incentives.html.erb
<%= render "research_sessions/progress" %>
<div class="main-content">
  <%= render 'error_summary' %>
  <h1 class="subtitle-large">Incentives</h1>
  <%= barnardos_form_with model: @research_session, url: wizard_path do |form| %>
      <%= form.radio_group_vertical :incentive,
          { true => 'Yes', false => 'No' },
          { autofocus_first_item: true },
          legend: 'Will an incentive be provided?'
      %>

      <%= form.radio_group_vertical :payment_type,
          PaymentType::NAME_VALUES,
          legend: 'What form will the incentive take?'
      %>

      <%= form.labelled_text_field :incentive_value %>

      <%= render 'button_bar' %>
  <% end %>
</div>

app/views/research_sessions/methodologies.html.erb
<%= render "research_sessions/progress" %>
<div class="main-content">
  <%= render 'error_summary' %>
  <h1 class="subtitle-large">Methodologies</h1>
  <%= barnardos_form_with model: @research_session, url: wizard_path do |form| %>
      <%= form.checkbox_group_vertical(
            :methodologies,
            Methodologies::NAME_VALUES,
            { autofocus_first_item: true },
            legend: 'How will you be gathering information?'
          )
      %>

      <div class="js-ConditionalSubfield"
           data-controlled-by="research_session[methodologies][]"
           data-control-value="other">
        <%= form.labelled_text_field :other_methodology %>
      </div>

      <%= render 'button_bar' %>
  <% end %>
</div>

app/views/research_sessions/preview.html.erb
<% ct = "preview.#{@research_session.able_to_consent_key}" %>

<%= c('Preview') do %>

  <%= c('PreviewInformation') do %>
    <div class="PreviewInformation-section">
      <%= c('Title', text: t('preview.title')) %>

      <% t("#{ct}.consent_control").each do |text| %>
        <%= c('Paragraph') do %>
          <%= raw text %>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <%= c('PreviewConsentForm') do %>
    <%= c('PrintArea') do %>
      <%= c('PreviewSection') do %>
        <%= c('Title', text: t("#{ct}.consent_form.title")) %>
        <%= c('Paragraph') do %>
          <%= raw t(
            "#{ct}.consent_form.the_research",
            topic: c(
              'Output',
              text: @research_session.topic,
              field: 'topic',
              url: edit_link_for(:topic)
            ),
            purpose: c(
              'Output',
              text: @research_session.purpose,
              field: 'purpose',
              url: edit_link_for(:purpose)
            )
          ) %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.consent_form.would_like_participant") %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.consent_form.young_people") %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.consent_form.voluntary") %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.consent_form.change_mind") %>
        <% end %>
      <% end %>


      <%= c('PreviewSection') do %>
        <%= c('HeadingOne', text: t("#{ct}.the_research.heading")) %>
        <%= c('Paragraph') do %>
          <%= raw t(
            "#{ct}.the_research.take_part_in",
            researcher_name: c(
              'Output',
              text: @research_session.researcher_name,
              field: 'researcher_name',
              url: edit_link_for(:researcher_name)
            ),
            researcher_job_title: c(
              'Output',
              text: @research_session.researcher_job_title,
              field: 'researcher_job_title',
              url: edit_link_for(:researcher_job_title)
            )
          ) %>
        <% end %>
        <%= c('UnorderedList') do %>
          <% @research_session.methodologies.each do |methodology| %>
            <%
              methodology_text =
                methodology === 'other' ?
                  @research_session.other_methodology
                  :
                  t("#{ct}.the_research.methodologies.#{methodology}")
            %>
            <%= c('ListItem') do %>
              <%= c(
                'Output',
                text: methodology_text,
                field: 'methodologies',
                url: edit_link_for(:methodologies)
              ) %>
            <% end %>
          <% end %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.the_research.record_using") %>
        <% end %>
        <%= c('UnorderedList') do %>
          <% @research_session.recording_methods.each do |recording_method| %>
            <%
              recording_text =
                recording_method === 'other' ?
                  @research_session.other_recording_method
                  :
                  t("#{ct}.the_research.recording_methods.#{recording_method}")
            %>
            <%= c('ListItem') do %>
              <%= c(
                'Output',
                text: recording_text,
                field: 'recording_methods',
                url: edit_link_for(:recording_methods)
              ) %>
            <% end %>
          <% end %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= raw t(
            "#{ct}.the_research.may_be_contacted",
            researcher_name: c(
              'Output',
              text: @research_session.researcher_name,
              field: 'researcher_name',
              url: edit_link_for(:researcher_name)
            )
          ) %>
        <% end %>
        <%= c('UnorderedList') do %>
          <%= c('ListItem') do %>
            <%= raw t(
              "#{ct}.the_research.contacted_by.email",
              email: c(
                'Output',
                text: @research_session['researcher_email'],
                field: 'researcher_email',
                url: edit_link_for(:researcher_email)
              )
            ) %>
          <% end %>
          <%= c('ListItem') do %>
            <%= raw t(
              "#{ct}.the_research.contacted_by.phone",
              phone: c(
                'Output',
                text: @research_session['researcher_phone'],
                field: 'researcher_phone',
                url: edit_link_for(:researcher_phone)
              )
            ) %>
          <% end %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.the_research.other_researchers") %>
        <% end %>
      <% end %>

       <% if @research_session.incentives_enabled ||
            @research_session.where_when_enabled ||
            @research_session.expenses_enabled %>
        <%= c('PreviewSection') do %>
          <%= c('HeadingOne', text: t("#{ct}.the_session.heading")) %>

          <% if @research_session.where_when_enabled %>
            <% [:when_text, :location, :duration].each do |field| %>
              <% if @research_session["#{field}"].present? %>
                <%= c('Paragraph') do %>
                  <%= raw t("#{ct}.the_session.#{field}") % [
                    c(
                      'Output',
                      text: @research_session["#{field}"],
                      field: field,
                      url: edit_link_for(field)
                    )
                  ] %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>

          <% if @research_session.where_when_enabled && @research_session.participant_equipment.present? %>
            <%= c('Paragraph') do %>
              <%= raw t("#{ct}.the_session.participant_equipment", equipment: c(
                'Output',
                text: @research_session.participant_equipment,
                field: 'participant_equipment',
                url: edit_link_for(:participant_equipment)
              )) %>
            <% end %>
          <% end %>

          <% if @research_session.expenses_enabled %>
            <%
              expenses = [
                :travel_expenses_limit,
                :food_expenses_limit,
                :other_expenses_limit
              ]
              .select { |expense_type| @research_session[expense_type].present? }
              .map { |expense_type|
                c(
                  'Output',
                  text: t("#{ct}.the_session.#{expense_type}", value: number_to_currency(@research_session[expense_type])),
                  field: expense_type,
                  url: edit_link_for(expense_type)
                )
              }
              .to_sentence
            %>

            <%= c('Paragraph') do %>
              <%= raw t("#{ct}.the_session.expenses", expenses: expenses) %>
            <% end %>

            <% if @research_session.receipts_required %>
              <%= c('Paragraph') do %>
                <%= c(
                  'Output',
                  text: t("#{ct}.the_session.receipts_required"),
                  field: 'receipts_required',
                  url: edit_link_for(:receipts_required)
                ) %>
              <% end %>
            <% end %>

            <% if @research_session.where_when_enabled && @research_session.food_provided.present? %>
              <%= c('Paragraph') do %>
                <%= raw t("#{ct}.the_session.food_provided", food: c(
                  'Output',
                  text: @research_session.food_provided,
                  field: 'food_provided',
                  url: edit_link_for(:food_provided)
                )) %>
              <% end %>
            <% end %>

            <% if @research_session.incentives_enabled %>
              <%= c('Paragraph') do %>
                <%= raw t(
                  "#{ct}.the_session.incentive",
                  value: c(
                    'Output',
                    text: number_to_currency(@research_session.incentive_value),
                    field: 'incentive_value',
                    url: edit_link_for(:incentive_value)
                  ),
                  payment_type: c(
                    'Output',
                    text: t("#{ct}.the_session.payment_type.#{@research_session.payment_type}"),
                    field: 'payment_type',
                    url: edit_link_for(:payment_type)
                  )
                ) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

      <%= c('PreviewSection') do %>
        <%= c('HeadingOne', text: t("#{ct}.personal_data.heading")) %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.personal_data.intro") %>
        <% end %>
        <%= c('UnorderedList') do %>
          <% t("#{ct}.personal_data.people_present").each do |text| %>
            <%= c('ListItem') do %>
              <%= text %>
            <% end %>
          <% end %>
        <% end %>
        <%= c('Paragraph') do %>
          <%=
            c(
              'Output',
              text: t("#{ct}.personal_data.shared_with.#{@research_session.shared_with}"),
              field: 'shared_with',
              url: edit_link_for(:shared_with)
            )
          %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= raw t("#{ct}.personal_data.shared_duration", duration: c(
            'Output',
            text: @research_session.shared_duration,
            field: 'shared_duration',
            url: edit_link_for(:shared_duration)
          )) %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.personal_data.contact") %>
        <% end %>
        <%= c('UnorderedList') do %>
          <% t("#{ct}.personal_data.contact_details").each do |text| %>
            <%= c('ListItem') do %>
              <%= text %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

      <%= c('PreviewSection') do %>
        <%= c('HeadingOne', text: t("#{ct}.safeguarding.heading")) %>
        <% t("#{ct}.safeguarding.paragraphs").each do |text| %>
          <%=
            c('Paragraph') do
              text
            end
          %>
        <% end %>
      <% end %>
    <% end %>

    <%= c('PrintArea') do %>
      <%= c('PreviewSection') do %>
        <%= c('HeadingOne', text: t("#{ct}.giving_your_consent.heading")) %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.giving_your_consent.intro") %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.giving_your_consent.i_understand") %>
        <% end %>
        <%= c('UnorderedList') do %>
          <%= c('ListItem') do %>
            <%= t("#{ct}.giving_your_consent.participation") %>
          <% end %>
          <%= c('ListItem') do %>
            <%
              recording_methods =
                @research_session.recording_methods
                  .map { |recording_method|
                    if recording_method === 'other'
                      c(
                        'Output',
                        text: @research_session.other_recording_method,
                        field: 'other_recording_method',
                        url: edit_link_for(:other_recording_method)
                      )
                    else
                      c(
                        'Output',
                        text:  t("#{ct}.the_research.recording_methods.#{recording_method}").downcase,
                        field: 'recording_methods',
                        url: edit_link_for(:recording_methods)
                      )
                    end
                  }
            %>
            <%= raw t("#{ct}.giving_your_consent.activities", recording_methods: recording_methods.to_sentence) %>
          <% end %>
          <%= c('ListItem') do %>
            <%= t("#{ct}.giving_your_consent.data") %>
          <% end %>
        <% end %>
        <%= c('Paragraph') do %>
          <%= t("#{ct}.giving_your_consent.i_agree") %>
        <% end %>
      <% end %>
      <%= c('WritingFields', fields: t("#{ct}.giving_your_consent.fields")) %>
    <% end %>
  <% end %>

  <%= c('PreviewInformation') do %>
    <div class="PreviewInformation-section">
      <%= c('Paragraph') do %>
        <%= c('PrintCommand', text: t('preview.print')) %>
      <% end %>
      <% t('preview.stuff').each_with_index do |text, index| %>
        <%= c('Paragraph') do %>
          <% if index == 0 %>
            <%= raw text % new_research_session_path(from_existing: @research_session.slug) %>
          <% elsif index == 3 %>
            <%= raw text % new_research_session_path %>
          <% else %>
            <%= raw text %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/research_sessions/recording.html.erb
<%= render "research_sessions/progress" %>
<div class="main-content">
  <%= render 'error_summary' %>
  <h1 class="subtitle-large">Recording</h1>
  <%= barnardos_form_with model: @research_session, url: wizard_path do |form| %>
      <%= form.checkbox_group_vertical(
            :recording_methods,
            RecordingMethods::NAME_VALUES,
            { autofocus_first_item: true },
            legend: 'How will you be recording information?'
          )
      %>

      <div class="js-ConditionalSubfield"
           data-controlled-by="research_session[recording_methods][]"
           data-control-value="other">
        <%= form.labelled_text_field :other_recording_method %>
      </div>

      <%= render 'button_bar' %>
  <% end %>
</div>

app/views/research_sessions/storing.html.erb
<%= render "research_sessions/progress" %>
<div class="main-content">
  <%= render 'error_summary' %>
  <h1 class="subtitle-large">Storing information</h1>
  <%= barnardos_form_with model: @research_session, url: wizard_path do |form| %>

    <%= form.radio_group_vertical \
        :shared_with,
        SharedWith::NAME_VALUES,
        { autofocus_first_item: true },
        legend: (raw I18n.t('research_session_attr_labels.shared_with') \
                     + '<br />' + I18n.t('research_session_attr_labels.shared_with_sublabel'))
    %>

    <%= form.labelled_text_field \
        :shared_duration, 
        (raw I18n.t('research_session_attr_labels.shared_duration') \
             + '<br />' + I18n.t('research_session_attr_labels.shared_duration_sublabel'))
    %>
    
    <%= render 'button_bar' %>
  <% end %>
</div>

app/views/research_sessions/time_equipment.html.erb
<%= render "research_sessions/progress" %>
<div class="main-content">
  <%= render 'error_summary' %>
  <h1 class="subtitle-large">Time and equipment</h1>
  <%= barnardos_form_with model: @research_session, url: wizard_path do |form| %>

    <fieldset class="datefield">
      <legend class="datefield__label">Please enter the time and date of the session (optional)</legend>
      <%= form.labelled_text_field \
               :when_text,
               text_options: {
                 placeholder: 'Monday 27th September 2017 at 3:00pm',
                 autofocus: true
               }
      %>
    </fieldset>

    <%= form.labelled_text_field :duration %>
    <%= form.labelled_text_field :location %>

    <%= form.labelled_text_area :participant_equipment %>

    <%= render 'button_bar' %>
  <% end %>
</div>

app/views/research_sessions/topic.html.erb
<%= render "research_sessions/progress" %>
<div class="main-content">
  <%= render 'error_summary' %>
  <h1 class="subtitle-large">Topic</h1>
  <%= barnardos_form_with model: @research_session, url: wizard_path do |form| %>
    <%= form.labelled_text_field(
          :topic,
          text_options: {
            placeholder: t('helpers.placeholder.research_session.topic'),
            autofocus: true
          }
        )
    %>

    <%= form.labelled_text_field(
          :purpose,
          text_options: {
            placeholder: t('helpers.placeholder.research_session.purpose'),
            autofocus: true
          }
        )
    %>

    <%= render 'button_bar' %>
  <% end %>
</div>